[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }

[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = ["--quiet", "-"] }
language-servers = ["pylsp"]

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "html"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "css"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls"]

[language-server.gopls]
command = "gopls"

[language-server.gopls.config.gopls]
analyses.unusedparams = true
analyses.shadow = true
analyses.unusedwrite = true
analyses.useany = true
staticcheck = true
gofumpt = true
usePlaceholders = true
completeUnimported = true
matcher = "CaseSensitive"
symbolMatcher = "FastFuzzy"

[language-server.gopls.config.gopls.hints]
# assignVariableTypes = true
# compositeLiteralFields = true
# compositeLiteralTypes = true
# constantValues = true
# functionTypeParameters = true
# parameterNames = true
# rangeVariableTypes = true

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "ini"
scope = "source.ini"
injection-regex = "ini"
file-types = ["conf", "ini", "cfg"]
roots = []
